version: '3.8'
services:
  app:
    container_name: flask_app
    build: .
    command: flask run --host=0.0.0.0 --port=80
    ports:
      - '80:80'
    depends_on:
      - db
    environment:
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
  db:
    container_name: flask_db
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  
